server:
  port: 8090
spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: reel.care4you@gmail.com
      password: thctnjolgzdxglgy
      properties:
        mail:
          smtp:
          auth: true
          starttls:
          enable: true